IF NOT EXISTS(SELECT 01 FROM sys.Tables WHERE Name = 'Funcionarios')
BEGIN
   CREATE TABLE common.Funcionarios (
      IdFuncionario SMALLINT IDENTITY(01, 01) NOT NULL,
      IdFuncaoFuncionario TINYINT NOT NULL,
      IdDescricaoHorario TINYINT NOT NULL,
      IdEstadoCivil TINYINT NULL,
      NomeFuncionario VARCHAR(100) NULL,
      DataAdmissao DATE NULL,
      DataDemissao DATE NULL,
      Sexo CHAR(01) NULL,
      DataNascimento DATE NULL,
      CPF CHAR(11),
      Email VARCHAR(80),
      Inativo BIT DEFAULT 00,
      NumeroCarteiraTrabalho VARCHAR(15) NULL,
      NumeroPisPasep VARCHAR(15) NULL,
      DigitoVerificadorPisPasep VARCHAR(03) NULL,
      NumeroSerie VARCHAR(05) NULL,
      DigitoVerificadorNumeroSerie VARCHAR(03) NULL,
      IdEstadoEmissao SMALLINT NULL,
      DataEmissaoCarteiraTrabalho DATE,
      LocalEmissaoCarteiraTrabalho VARCHAR(20),
      LogIdUsuario SMALLINT NOT NULL,
      LogRotina VARCHAR(01) NOT NULL,
      LogDataHora DATETIME DEFAULT (SYSDATETIME()),
      LogMotivoExclusao VARCHAR(MAX) NULL,
      ConCurrencyId VARCHAR(50) NOT NULL DEFAULT NEWID(),
   CONSTRAINT PK_Funcionarios PRIMARY KEY (IdFuncionario),
   CONSTRAINT FK_Funcionarios_FuncoesFuncionario FOREIGN KEY(IdFuncaoFuncionario) REFERENCES common.FuncoesFuncionario(IdFuncaoFuncionario),
   CONSTRAINT FK_Funcionarios_DescHorarios FOREIGN KEY(IdDescricaoHorario) REFERENCES common.DescricoesHorarios(IdDescricaoHorario),
   CONSTRAINT FK_Funcionarios_EstadosCivis FOREIGN KEY(IdEstadoCivil) REFERENCES common.EstadosCivis(IdEstadoCivil),
   CONSTRAINT FK_Funcionarios_Estados FOREIGN KEY(IdEstadoEmissao) REFERENCES enderecos.Estados(IdEstado),
   CONSTRAINT FK_Funcionarios_Usuarios FOREIGN KEY(LogIdUsuario) REFERENCES common.Usuarios(IdUsuario))
END