CREATE TABLE EnderecosPessoas (
   IdEnderecoPessoa INTEGER IDENTITY(01, 01),
   IdVia INTEGER NOT NULL,
   IdPessoa INTEGER NOT NULL,
   IdTipoEndereco TINYINT NOT NULL,
   IdLoteamento SMALLINT NULL,
   IdLote SMALLINT NULL,
   IdQuadra SMALLINT NULL,
   IdCondominio SMALLINT NULL,
   IdDistrito SMALLINT NULL,
   Numero INTEGER NULL,
   Complemento VARCHAR(25) NULL,
CONSTRAINT PK_EnderecosPessoas PRIMARY KEY(IdEnderecoPessoa),
CONSTRAINT FK_EnderecosPessoas_Vias FOREIGN KEY(IdVia) REFERENCES Vias(IdVia),
CONSTRAINT FK_EnderecosPessoas_Pessoas FOREIGN KEY(IdPessoa) REFERENCES Pessoas(IdPessoa),
CONSTRAINT FK_EnderecosPessoas_TiposEndereco FOREIGN KEY(IdTipoEndereco) REFERENCES TiposEndereco(IdTipoEndereco),
CONSTRAINT FK_EnderecosPessoas_Loteamentos FOREIGN KEY(IdLoteamento) REFERENCES Loteamentos(IdLoteamento),
CONSTRAINT FK_EnderecosPessoas_Lotes FOREIGN KEY(IdLote) REFERENCES Lotes(IdLote),
CONSTRAINT FK_EnderecosPessoas_Quadras FOREIGN KEY(IdQuadra) REFERENCES Quadras(IdQuadra),
CONSTRAINT FK_EnderecosPessoas_Condominios FOREIGN KEY(IdCondominio) REFERENCES Condominios(IdCondominio),
CONSTRAINT FK_EnderecosPessoas_Distritos FOREIGN KEY(IdDistrito) REFERENCES Distritos(IdDistrito))