CREATE TABLE IF NOT EXISTS IMPOSTOS (
   ID_IMPOSTO TINYINT NOT NULL AUTO_INCREMENT, --CodigoTaxa
   DESC_IMPOSTO VARCHAR(30) NULL, --DescricaoTaxa
   ABREV_IMPOSTO VARCHAR(20) NULL, --Abreviatura
   NOME_FORMULA VARCHAR(20) NULL, --NomeFormula
   SEQUENCIA TINYINT NULL, --Posicao
   COD_RECEITA VARCHAR(20), --CodigoReceita
   VALOR_INTEGRAL BOOLEAN NULL, --ValorIntegral
   ENVIAR_DIVIDA BOOLEAN NULL, --Enviar
   INCIDE_DESCONTO BOOLEAN NULL, --IncideDesconto
   CLASSIFICACAO CHAR(01) NULL, --Classificacao
   COD_RECEITA_DIVIDA VARCHAR(04) NULL, --CodigoGeral
   INCIDIR_ISENCAO BOOLEAN NULL, --IncidirIsencao
   CONSIDERAR_SUB_UNIDADE BOOLEAN, --ConsiderarSubUnidade
   RECEITA_ITU BOOLEAN,
CONSTRAINT PK_IMPOSTOS PRIMARY KEY(ID_IMPOSTO))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS IMPOSTOS_LOG (
   ID_IMPOSTO_LOG INTEGER NOT NULL AUTO_INCREMENT,
   ID_IMPOSTO TINYINT NOT NULL,
   ROTINA_LOG CHAR(01) NULL,
   USER_LANCAMENTO VARCHAR(20) NOT NULL,
   DATA_LANCAMENTO DATE NOT NULL,
   HORA_LANCAMENTO TIME NOT NULL,
   IP_LANCAMENTO VARCHAR(32) NOT NULL,
   RECUPERADO BOOLEAN NULL,
   USER_RECUPERADO VARCHAR(20) NOT NULL,
   MOTIVO_EXCLUSAO TEXT NULL,
   DADOS_ALTERADOS_EXCLUIDOS TEXT NULL,
   SCRIPT_INSERT_UPDATE TEXT NULL,
CONSTRAINT PK_IMPOSTOS_LOG PRIMARY KEY(ID_IMPOSTO_LOG, ID_IMPOSTO))
ENGINE = MyISAM;