INSERT INTO enderecos.Logradouros (DescricaoLogradouro, AbreviaturaLogradouro, LogIdUsuario, LogRotina)
VALUES ('ACAMPAMENTO',          'ACAMP',    01, 'I')
      ,('ACESSO',               'AC',       01, 'I')
      ,('ADRO',                 'AD',       01, 'I')
      ,('AEROPORTO',            'ERA',      01, 'I')
      ,('ALAMEDA',              'AL',       01, 'I')
      ,('ALTO',                 'AT',       01, 'I')
      ,('AREA',                 'A',        01, 'I')
      ,('AREA ESPECIAL',        'AE',       01, 'I')
      ,('ARTERIA',              'ART',      01, 'I')
      ,('ATALHO',               'ATL',      01, 'I')
      ,('AVENIDA',              'AV',       01, 'I')
      ,('AVENIDA CONTORNO',     'AV-CONT',  01, 'I')
      ,('BAIXA',                'BX',       01, 'I')
      ,('BALAO',                'BLO',      01, 'I')
      ,('BALNEARIO',            'BAL',      01, 'I')
      ,('BECO',                 'BC',       01, 'I')
      ,('BELVEDERE',            'BELV',     01, 'I')
      ,('BLOCO',                'BL',       01, 'I')
      ,('BOSQUE',               'BSQ',      01, 'I')
      ,('BOULEVARD',            'BVD',      01, 'I')
      ,('BURACO',               'BCO',      01, 'I')
      ,('CAIS',                 'C',        01, 'I')
      ,('CALCADA',              'CALC',     01, 'I')
      ,('CAMINHO',              'CAM',      01, 'I')
      ,('CAMPO',                'CPO',      01, 'I')
      ,('CANAL',                'CAN',      01, 'I')
      ,('CHACARA',              'CHAP',     01, 'I')
      ,('CHAPADAO',             'CHAP',     01, 'I')
      ,('CIRCULAR',             'CIRC',     01, 'I')
      ,('COLONIA',              'COL',      01, 'I')
      ,('COMPLEXO VIARIO',      'CMP-VR',   01, 'I')
      ,('CONDOMINIO',           'COND',     01, 'I')
      ,('CONJUNTO',             'CJ',       01, 'I')
      ,('CORREDOR',             'COR',      01, 'I')
      ,('CORREGO',              'CRG',      01, 'I')
      ,('DESCIDA',              'DSC',      01, 'I')
      ,('DESVIO',               'DSV',      01, 'I')
      ,('DISTRITO',             'DT',       01, 'I')
      ,('ELEVADA',              'EVD',      01, 'I')
      ,('ENTRADA PARTICULAR',   'ENT-PART', 01, 'I')
      ,('ENTRE QUADRA',         'EQ',       01, 'I')
      ,('ESCADA',               'ESC',      01, 'I')
      ,('ESPLANADA',            'ESP',      01, 'I')
      ,('ESTACAO',              'ETC',      01, 'I')
      ,('ESTACIONAMENTO',       'ESTC',     01, 'I')
      ,('ESTADIO',              'ETD',      01, 'I')
      ,('ESTANCIA',             'ETN',      01, 'I')
      ,('ESTRADA',              'EST',      01, 'I')
      ,('ESTRADA MUNICIPAL',    'EST-MUN',  01, 'I')
      ,('FAVELA',               'FAV',      01, 'I')
      ,('FAZENDA',              'FAZ',      01, 'I')
      ,('FEIRA',                'FRA',      01, 'I')
      ,('FERROVIA',             'FER',      01, 'I')
      ,('FONTE',                'FNT',      01, 'I')
      ,('FORTE',                'FTE',      01, 'I')
      ,('GALERIA',              'GAL',      01, 'I')
      ,('GRANJA',               'GJA',      01, 'I')
      ,('HABITACIONAL',         'HAB',      01, 'I')
      ,('ILHA',                 'IA',       01, 'I')
      ,('JARDIM',               'JD',       01, 'I')
      ,('JARDINETE',            'JDE',      01, 'I')
      ,('LADEIRA',              'LD',       01, 'I')
      ,('LAGO',                 'LG',       01, 'I')
      ,('LAGOA',                'LGA',      01, 'I')
      ,('LARGO',                'LRG',      01, 'I')
      ,('LOTEAMENTO',           'LOT',      01, 'I')
      ,('MARINA',               'MNA',      01, 'I')
      ,('MODULO',               'MOD',      01, 'I')
      ,('MONTE',                'TEM',      01, 'I')
      ,('MORRO',                'MRO',      01, 'I')
      ,('NUCLEO',               'NUC',      01, 'I')
      ,('PARADA',               'PDA',      01, 'I')
      ,('PARADOURO',            'PDO',      01, 'I')
      ,('PARALELA',             'PAR',      01, 'I')
      ,('PARQUE',               'PRQ',      01, 'I')
      ,('PASSAGEM',             'PSG',      01, 'I')
      ,('PASSAGEM SUBTERRANEA', 'PSC-SUB',  01, 'I')
      ,('PASSARELA',            'PSA',      01, 'I')
      ,('PASSEIO',              'PAS',      01, 'I')
      ,('PATIO',                'PAT',      01, 'I')
      ,('PONTA',                'PNT',      01, 'I')
      ,('PONTE',                'PTE',      01, 'I')
      ,('PORTO',                'PTO',      01, 'I')
      ,('PRACA',                'PC',       01, 'I')
      ,('PRACA DE ESPORTES',    'PC-ESP',   01, 'I')
      ,('PRAIA',                'PR',       01, 'I')
      ,('PROLONGAMENTO',        'PRL',      01, 'I')
      ,('QUADRA',               'Q',        01, 'I')
      ,('QUINTA',               'QTA',      01, 'I')
      ,('QUINTA',               'QTAS',     01, 'I')
      ,('RAMAL',                'RAM',      01, 'I')
      ,('RAMPA',                'RMP',      01, 'I')
      ,('RECANTO',              'REC',      01, 'I')
      ,('RESIDENCIAL',          'RES',      01, 'I')
      ,('RETA',                 'RET',      01, 'I')
      ,('RETIRO',               'RER',      01, 'I')
      ,('RETORNO',              'RTN',      01, 'I')
      ,('RODO ANEL',            'ROD-AN',   01, 'I')
      ,('RODOVIA',              'ROD',      01, 'I')
      ,('ROTATORIA',            'RTT',      01, 'I')
      ,('ROTULA',               'ROT',      01, 'I')
      ,('RUA',                  'R',        01, 'I')
      ,('RUA DE LIGACAO',       'R-LIG',    01, 'I')
      ,('RUA DE PEDESTRE',      'R-PED',    01, 'I')
      ,('SERVIDAO',             'SRV',      01, 'I')
      ,('SETOR',                'ST',       01, 'I')
      ,('SITIO',                'SIT',      01, 'I')
      ,('SUBIDA',               'SUB',      01, 'I')
      ,('TERMINAL',             'TER',      01, 'I')
      ,('TRAVESSA',             'TV',       01, 'I')
      ,('TRAVESSA PARTICULAR',  'TV-PART',  01, 'I')
      ,('TRECHO',               'TRCH',     01, 'I')
      ,('TREVO',                'TRV',      01, 'I')
      ,('TRINCHEIRA',           'TCH',      01, 'I')
      ,('TUNEL',                'TUN',      01, 'I')
      ,('UNIDADE',              'UNID',     01, 'I')
      ,('VALA',                 'VAL',      01, 'I')
      ,('VALE',                 'VLE',      01, 'I')
      ,('VARIANTE',             'VRTE',     01, 'I')
      ,('VEREDA',               'VER',      01, 'I')
      ,('VIA',                  'V',        01, 'I')
      ,('VIA DE ACESSO',        'V-AC',     01, 'I')
      ,('VIA DE PEDESTRE',      'V-PED',    01, 'I')
      ,('VIA ELEVADO',          'V-EVD',    01, 'I')
      ,('VIA EXPRESSA',         'V-EXP',    01, 'I')
      ,('VIADUTO',              'VD',       01, 'I')
      ,('VIELA',                'VLA',      01, 'I')
      ,('VILA',                 'VL',       01, 'I')
      ,('ZIGUE-ZAGUE',          'ZIG-ZAG',  01, 'I')