INSERT INTO FORMAS_PAGTOS(NOME_FORMA_PAGTO) VALUES
('NÃO INFORMADA'),
('DINHEIRO'),
('CHEQUE'),
('CARTÃO DE DÉBITO'),
('CARTÃO DE CRÉDITO'),
('DOC - DOCUMENTO DE ORDEM DE CRÉDITO'),
('TED - TRANSFERÊNCIA ELETRÔNICA DISPONÍVEL'),
('BOLETO BANCÁRIO'),
('TRAVELER''S MONEY'),
('PAYPAL'),
('PAGSEGURO'),
('TRANSFERÊNCIA BANCÁRIA'),
('DEPÓSITO BANCÁRIO');

